// Code generated by builder-gen. DO NOT EDIT.
package errutil

func (o Opts) HasTags() bool {
	return o.Tags != nil
}

func (o Opts) HasStackTrace() bool {
	return o.StackTrace != nil
}

func (o Opts) HasInternalErrorMessage() bool {
	return o.InternalErrorMessage != nil
}

func (o Opts) HasCode() bool {
	return o.Code != nil
}

func (o Opts) HasStatusCode() bool {
	return o.StatusCode != nil
}

type OptsFunc func(*Opts)

func ToOpts(opts ...OptsFunc) Opts {
	var info Opts
	ToOptsWithDefault(&info, opts...)

	return info
}

func ToOptsWithDefault(info *Opts, opts ...OptsFunc) {
	for _, o := range opts {
		o(info)
	}
}

func WithAccessDenied(accessDeniedParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.AccessDenied = len(accessDeniedParam) == 0 || accessDeniedParam[0]
	}
}

func WithConflict(conflictParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.Conflict = len(conflictParam) == 0 || conflictParam[0]
	}
}

func WithNotFound(notFoundParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.NotFound = len(notFoundParam) == 0 || notFoundParam[0]
	}
}

func WithExists(existsParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.Exists = len(existsParam) == 0 || existsParam[0]
	}
}

func WithTooLarge(tooLargeParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.TooLarge = len(tooLargeParam) == 0 || tooLargeParam[0]
	}
}

func WithRateLimit(rateLimitParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.RateLimit = len(rateLimitParam) == 0 || rateLimitParam[0]
	}
}

func WithTags(tagsParam ...Tag) OptsFunc {
	return func(opts *Opts) {
		opts.Tags = tagsParam
	}
}

func WithStackTrace(stackTraceParam int) OptsFunc {
	return func(opts *Opts) {
		opts.StackTrace = &stackTraceParam
	}
}

func WithUnauthorized(unauthorizedParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.Unauthorized = len(unauthorizedParam) == 0 || unauthorizedParam[0]
	}
}

func WithTemporary(temporaryParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.Temporary = len(temporaryParam) == 0 || temporaryParam[0]
	}
}

func WithInternalErrorMessage(internalErrorMessageParam string) OptsFunc {
	return func(opts *Opts) {
		opts.InternalErrorMessage = &internalErrorMessageParam
	}
}

func WithCode(codeParam string) OptsFunc {
	return func(opts *Opts) {
		opts.Code = &codeParam
	}
}

func WithStatusCode(statusCodeParam int) OptsFunc {
	return func(opts *Opts) {
		opts.StatusCode = &statusCodeParam
	}
}

func WithTooManyRequests(tooManyRequestsParam ...bool) OptsFunc {
	return func(opts *Opts) {
		opts.TooManyRequests = len(tooManyRequestsParam) == 0 || tooManyRequestsParam[0]
	}
}
