// Code generated by builder-gen. DO NOT EDIT.
package errutil

type OptsFunc func(*Opts)

func ToOpts(opts ...OptsFunc) Opts {
	var info Opts
	ToOptsWithDefault(&info, opts...)

	return info
}

func ToOptsWithDefault(info *Opts, opts ...OptsFunc) {
	for _, o := range opts {
		o(info)
	}
}

func WithAccessDenied(accessDeniedParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.AccessDenied = accessDeniedParam
	}
}

func WithConflict(conflictParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.Conflict = conflictParam
	}
}

func WithNotFound(notFoundParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.NotFound = notFoundParam
	}
}

func WithExists(existsParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.Exists = existsParam
	}
}

func WithTooLarge(tooLargeParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.TooLarge = tooLargeParam
	}
}

func WithRateLimit(rateLimitParam bool) OptsFunc {
	return func(opts *Opts) {
		opts.RateLimit = rateLimitParam
	}
}
